# Pages CMS Configuration (.pages.yml)
# This configuration defines posts and authors with proper relational references
 
# Media configuration
media:
  input: static/media
  output: /media
 
# Content collections
content:
  # Posts collection
  - name: posts
    label: Blog Posts
    type: collection
    path: content/posts
    filename: "{year}-{month}-{day}-{slug}"
    view:
      fields: [title, date, author, published]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
 
      - name: slug
        label: URL Slug
        type: string
        required: true
        pattern:
          regex: '^[a-z0-9-]+$'
          message: 'Slug must contain only lowercase letters, numbers, and hyphens'
 
      - name: date
        label: Publish Date
        type: date
        required: true
        default: "now"
 
      - name: author
        label: Author
        type: reference
        required: false
        options:
          collection: authors
          value: slug
          display: name
          search: [name]
 
      - name: tags
        label: Tags
        type: string
        list: true
 
      - name: body
        label: Content
        type: rich-text
        required: true
 
  # Authors collection
  - name: authors
    label: Authors
    type: collection
    path: content/authors
    filename: "{slug}"
    view:
      fields: [name]
      primary: name
      sort: [name]
      default:
        sort: name
        order: asc
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
 
      - name: slug
        label: URL Slug
        type: string
        required: true
        pattern:
          regex: '^[a-z0-9-]+$'
          message: 'Slug must contain only lowercase letters, numbers, and hyphens'

      - name: posts
        label: Posts
        type: reference
        required: true
        options:
          collection: posts
          display: name
          search: [name]

 
# Reusable components
components:
  social_link:
    label: Social Media Link
    type: object
    fields:
      - name: platform
        label: Platform
        type: select
        required: true
        options:
          options:
            - label: Twitter
              value: twitter
            - label: LinkedIn
              value: linkedin
            - label: GitHub
              value: github
            - label: Instagram
              value: instagram
            - label: Facebook
              value: facebook
 
      - name: url
        label: URL
        type: string
        required: true
        pattern:
          regex: '^https?://.+'
          message: 'Please enter a valid URL'
 
  contact_info:
    label: Contact Information
    type: object
    fields:
      - name: email
        label: Email
        type: string
        component: email
 
      - name: phone
        label: Phone Number
        type: string
 
      - name: address
        label: Address
        type: text
 
  email:
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com)'
 
# Global settings
settings:
  content:
    merge: false